set -e
pdflatex lni.dtx
pdflatex lni.dtx
touch mybibfile.bib
pdflatex lni-author-template
pdflatex lni-paper-example-de
/usr/local/texlive/2023/bin/x86_64-linuxmusl/biber lni-paper-example-de
pdflatex lni-paper-example-de
pdflatex lni-paper-example-de
