#!/bin/bash
# Use this file (on a unix system) to generate the zip archive for CTAN
# ctanify is part of TeX Live and MiKTeX distributions
# Please note, that you need at least version 1.9 to add the symbolic link correctly.
#
echo "Make sure we have the latest version"
pdflatex lni.dtx
echo "Make sure all links in lni.pdf are correct"
pdflatex lni.dtx
if [ -f lni.tar.gz ]; then
   echo "Remove old archive"
   rm lni.tar.gz
fi
rm -f lni-instructions.pdf
ln -s -f lni.pdf lni-instructions.pdf
ctanify --no-tds lni.ins lni.pdf README.md CHANGELOG.md CONTRIBUTING.md "lni-instructions.pdf=doc/latex/lni" "lni-author-template.tex=doc/latex/lni" "lni-paper-example-de.tex=doc/latex/lni" "lni-paper-example-de.bib=doc/latex/lni" "lni.bst=bibtex/bst/lni" "lnig.bst=bibtex/bst/lni"
