name: check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           package_file: Texlivefile
  build:
    needs: [cache]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        engine: [pdflatex, lualatex]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           package_file: Texlivefile
      - name: Generate lni.cls, *.tex, ...
        run: |
          pdflatex lni.ins
          pdflatex lni.dtx
          pdflatex lni.dtx
          pdflatex lni.dtx
      - name: Check for modifications
        run: |
          git update-index --refresh
          if ! git diff-index --quiet HEAD --; then
            echo "Worktree is not clean."
            git diff-index --name-status HEAD
            exit 1
          fi

      - name: Generate mybibfile.bib
        run: touch mybibfile.bib

      # lni-author-template
      - run: ${{ matrix.engine }} lni-author-template
      - run: texlogsieve lni-author-template.log

      # lni-paper-example-de
      - run: ${{ matrix.engine }} lni-paper-example-de
      - run: biber lni-paper-example-de
      - run: ${{ matrix.engine }} lni-paper-example-de
      - run: ${{ matrix.engine }} lni-paper-example-de
      - run: texlogsieve lni-paper-example-de.log

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: PDFs-${{ matrix.engine }}
          path: |
            lni-author-template.pdf
            lni-paper-example*.pdf
            *.log

      - name: Prepare GH pages content
        if: github.ref == 'refs/heads/main' && matrix.engine == 'lualatex'
        run: |
          set -e
          mkdir /tmp/gh-pages
          cp README.md /tmp/gh-pages/index.md
          cp *.pdf /tmp/gh-pages

      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' && matrix.engine == 'lualatex'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/gh-pages

      - name: Install dependencies for ctanify
        if: matrix.engine != 'lualatex'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libfile-copy-recursive-perl
          version: 1.0

      - name: Prepare for CTAN
        if: matrix.engine != 'lualatex'
        run: ./prepare_for_CTAN

      - name: Upload CTAN build
        if: matrix.engine != 'lualatex'
        uses: actions/upload-artifact@v4
        with:
          name: CTAN-${{ matrix.engine }}
          path: '*.tar.gz'
  changelog:
    name: CHANGELOG.md
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - uses: jbangdev/jbang-action@v0.115.0
        with:
          script: com.github.nbbrd.heylogs:heylogs-cli:0.7.2:bin
          scriptargs: "check CHANGELOG.md"
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
